repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.4
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
  hooks:
    # Check commit message follows Conventional Commits
    - id: commitizen
      stages: [commit-msg]
