/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_test_JNITest */

#ifndef _Included_com_ndk_test_JNITest
#define _Included_com_ndk_test_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_test_JNITest
 * Method:    AddString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_test_JNITest_AddString
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ndk_test_JNITest
 * Method:    AddInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ndk_test_JNITest_AddInt
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
