LOCAL_FFTW3_PATH := $(call my-dir)

### fftw3f
LOCAL_PATH := $(LOCAL_FFTW3_PATH)
include $(CLEAR_VARS)

LOCAL_MODULE := libfftw3f
LOCAL_SRC_FILES := lib/libfftw3f.a
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include

LOCAL_EXPORT_C_INCLUDES += $(LOCAL_C_INCLUDES)
LOCAL_EXPORT_LDLIBS     := $(LOCAL_LDLIBS)
LOCAL_EXPORT_CFLAGS     := $(LOCAL_CFLAGS)
LOCAL_EXPORT_CPPFLAGS   := $(LOCAL_CPPFLAGS)

include $(PREBUILT_STATIC_LIBRARY)
