/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_test_OpenCVTest */

#ifndef _Included_com_ndk_test_OpenCVTest
#define _Included_com_ndk_test_OpenCVTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_test_OpenCVTest
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ndk_test_OpenCVTest_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
