/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_test_NEONTest */

#ifndef _Included_com_ndk_test_NEONTest
#define _Included_com_ndk_test_NEONTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_test_NEONTest
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ndk_test_NEONTest_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
