[tool.poetry]
name = "libccv"
version = "1.0.0"
description = "Open Chenguang Computer Vision library in Python"
authors = ["Gavin Gao <cggos@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
