/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_test_FFTW3 */

#ifndef _Included_com_ndk_test_FFTW3
#define _Included_com_ndk_test_FFTW3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_test_FFTW3
 * Method:    DFT2DfromPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ndk_test_FFTW3_DFT2DfromPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ndk_test_FFTW3
 * Method:    DFT2DfromAddr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ndk_test_FFTW3_DFT2DfromAddr
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
