depth_registration: true

rgb_processing                 : true
ir_processing                  : false
depth_processing               : false
depth_registered_processing    : false
disparity_processing           : false
disparity_registered_processing: false
hw_registered_processing       : false
sw_registered_processing       : false

